### ISSUE TITLE
Unable to deploy 

### ISSUE THREAD

**Issue by bruceMacLeod** [munk/openhds-ui#153]
Followed the instructions on : https://github.com/munk/openhds-ui

When I attempted to start the server with docker run -p 3000:3000 -it ohdsui   The following error occurred : 
<img width="572" alt="screen shot 2016-11-15 at 7 22 01 pm" src="https://cloud.githubusercontent.com/assets/1298797/20329916/2dbfd464-ab69-11e6-951b-807f639db11b.png">

Any suggestions ?

**Comment by munk** [comment]
The problem is the npm modules aren't installed. It looks like those commands are missing from the container.

**Comment by munk** [comment]
I'm able to reproduce it locally. I'll push a fix shortly.

**Comment by munk** [comment]
If you'd like to run it before I have the fix, run `npm install` in the root and /app directories, then npm start from the root directory.

**Comment by munk** [comment]
@bruceMacLeod
I believe this commit fixes the issue. Can you confirm it works for you now after you pull master?

 https://github.com/munk/openhds-ui/commit/a43f0a308e9643a3d20afdbf118d01c8b07a96de

**Comment by bruceMacLeod** [comment]
Tried npm install, got this : 

<img width="604" alt="screen shot 2016-11-16 at 6 16 28 am" src="https://cloud.githubusercontent.com/assets/1298797/20345265/5bcd84e0-abc4-11e6-851c-bb3cd4dafc8e.png">

Probably do not have the time to debug this am. 

[npm-debug.txt](https://github.com/munk/openhds-ui/files/594441/npm-debug.txt)

**Comment by bruceMacLeod** [comment]
Did another pull & same error as original comment.

**Comment by bruceMacLeod** [comment]
Able to deploy now.  Had to reinstalling npm using these instructions : https://gist.github.com/DanHerbert/9520689

When I go to http://localhost:3000   I get a blank screen. Hmmm
